### ISSUE TITLE
Error: No route found for "POST /admin/": Method Not Allowed (Allow: GET) when deleting a process execution record

### ISSUE THREAD

**Issue by interuros** [dpfaffenbauer/ProcessManager#62]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

When deleting process executions from the admin panel i get this error: 

![image](https://user-images.githubusercontent.com/28816363/120097338-2fd4d380-c130-11eb-98b3-5b7fe1d757c1.png)

Deleting this line of code resolves this error, but then the record doesn't get deleted until list is refreshed:

![image](https://user-images.githubusercontent.com/28816363/120097402-893d0280-c130-11eb-955a-9714e495f151.png)

**Comment by dpfaffenbauer** [comment]
Has already been fixed in master

**Comment by interuros** [comment]
I installed the latest version via composer (**composer require dpfaffenbauer/process-manager:2.6.2**) but i still get the same error. I checked on your repository and it seems that your 2.6.2 tag that you deployed doesn't have that bug fixed, but your 2.6 branch has that bug fixed.

**Comment by dpfaffenbauer** [comment]
Fix has not been released yet!

https://github.com/dpfaffenbauer/ProcessManager/pull/60
